database: &DATABASE
  adapter: sqlite3
  encoding: utf8
  host: localhost
  timeout: 5000

development:
  <<: *DATABASE
  database: tagkast_dev
  username: root
  password:

production:
  <<: *DATABASE
  database: tagkast
  username: root
  password:

staging:
  <<: *DATABASE
  database: tagkast_staging
  username: root
  password:

test:
  <<: *DATABASE
  database: tagkast_test
  username: root
  password:

